export const tabItemData = [
  {
    name: "主站1",
    id: 0,
    InterfereTime: "", //时间
    grType: "压制干扰", //类型
    grpattern: "", //模式
    homePower: "", //功率
    form: {
      state1: false, //f1禁用
      state2: false, //f1禁用
      state3: false, //f1禁用
      pattern1: "",
      power1: "",
      standard1: "", //standard1
      frequency1: "",
      dpgrZbpl1: "",
      tpgrZbpl1: "",
      tpgrTzpl1: "",
      tpgrZbpp1: "",
      spgrQspl1: "",
      spgrZzpl1: "",
      spgrSpds1: "",
      spgrPdzlsj1: "",
      bzsgrZxpl1: "",
      bzsgrDk1: "",
      bzsgrLbqxs1: "",
      bzsgrLbqaz1: "",
      txgrZbpl1: "",
      txgrTxxs1: "",
      txgrFhsl1: "",
      txgrPNm1: "",
      txgrLbqxs1: "",
      txgrLbqaz1: "",
      mcgrMckd1: "",
      mcgrZq1: "",
      pattern2: "",
      power2: "",
      standard2: "", //form12
      frequency2: "",
      dpgrZbpl2: "",
      tpgrZbpl2: "",
      tpgrTzpl2: "",
      tpgrZbpp2: "",
      spgrQspl2: "",
      spgrZzpl2: "",
      spgrSpds2: "",
      spgrPdzlsj2: "",
      bzsgrZxpl2: "",
      bzsgrDk2: "",
      bzsgrLbqxs2: "",
      bzsgrLbqaz2: "",
      txgrZbpl2: "",
      txgrTxxs2: "",
      txgrFhsl2: "",
      txgrPNm2: "",
      txgrLbqxs2: "",
      txgrLbqaz2: "",
      mcgrMckd2: "",
      mcgrZq2: "",
      pattern3: "",
      power3: "",
      standard3: "", //form13
      frequency3: "",
      dpgrZbpl3: "",
      tpgrZbpl3: "",
      tpgrTzpl3: "",
      tpgrZbpp3: "",
      spgrQspl3: "",
      spgrZzpl3: "",
      spgrSpds3: "",
      spgrPdzlsj3: "",
      bzsgrZxpl3: "",
      bzsgrDk3: "",
      bzsgrLbqxs3: "",
      bzsgrLbqaz3: "",
      txgrZbpl3: "",
      txgrTxxs3: "",
      txgrFhsl3: "",
      txgrPNm3: "",
      txgrLbqxs3: "",
      txgrLbqaz3: "",
      mcgrMckd3: "",
      mcgrZq3: "",
    },
    form1: {
      f1Bit0: "",
      f1Bit1: "",
      f1Bit2: "",
      f1Bit3: "",
      f2Bit0: "",
      f2Bit1: "",
      f2Bit2: "",
      f2Bit3: "",
      f3Bit0: "",
      f3Bit1: "",
      f3Bit2: "",
      f3Bit3: "",
    },
  },
  {
    name: "从站1",
    id: 1,
    InterfereTime: "", //时间
    grType: "压制干扰", //类型
    grpattern: "", //模式
    homePower: "", //功率
    form: {
      state1: false, //f1禁用
      state2: false, //f1禁用
      state3: false, //f1禁用
      pattern1: "",
      power1: "",
      standard1: "", //standard1
      frequency1: "",
      dpgrZbpl1: "",
      tpgrZbpl1: "",
      tpgrTzpl1: "",
      tpgrZbpp1: "",
      spgrQspl1: "",
      spgrZzpl1: "",
      spgrSpds1: "",
      spgrPdzlsj1: "",
      bzsgrZxpl1: "",
      bzsgrDk1: "",
      bzsgrLbqxs1: "",
      bzsgrLbqaz1: "",
      txgrZbpl1: "",
      txgrTxxs1: "",
      txgrFhsl1: "",
      txgrPNm1: "",
      txgrLbqxs1: "",
      txgrLbqaz1: "",
      mcgrMckd1: "",
      mcgrZq1: "",
      pattern2: "",
      power2: "",
      standard2: "", //form12
      frequency2: "",
      dpgrZbpl2: "",
      tpgrZbpl2: "",
      tpgrTzpl2: "",
      tpgrZbpp2: "",
      spgrQspl2: "",
      spgrZzpl2: "",
      spgrSpds2: "",
      spgrPdzlsj2: "",
      bzsgrZxpl2: "",
      bzsgrDk2: "",
      bzsgrLbqxs2: "",
      bzsgrLbqaz2: "",
      txgrZbpl2: "",
      txgrTxxs2: "",
      txgrFhsl2: "",
      txgrPNm2: "",
      txgrLbqxs2: "",
      txgrLbqaz2: "",
      mcgrMckd2: "",
      mcgrZq2: "",
      pattern3: "",
      power3: "",
      standard3: "", //form13
      frequency3: "",
      dpgrZbpl3: "",
      tpgrZbpl3: "",
      tpgrTzpl3: "",
      tpgrZbpp3: "",
      spgrQspl3: "",
      spgrZzpl3: "",
      spgrSpds3: "",
      spgrPdzlsj3: "",
      bzsgrZxpl3: "",
      bzsgrDk3: "",
      bzsgrLbqxs3: "",
      bzsgrLbqaz3: "",
      txgrZbpl3: "",
      txgrTxxs3: "",
      txgrFhsl3: "",
      txgrPNm3: "",
      txgrLbqxs3: "",
      txgrLbqaz3: "",
      mcgrMckd3: "",
      mcgrZq3: "",
    },
    form1: {
      f1Bit0: "",
      f1Bit1: "",
      f1Bit2: "",
      f1Bit3: "",
      f2Bit0: "",
      f2Bit1: "",
      f2Bit2: "",
      f2Bit3: "",
      f3Bit0: "",
      f3Bit1: "",
      f3Bit2: "",
      f3Bit3: "",
    },
  },
  {
    name: "从站2",
    id: 2,
    InterfereTime: "", //时间
    grType: "压制干扰", //类型
    grpattern: "", //模式
    homePower: "", //功率
    form: {
      state1: false, //f1禁用
      state2: false, //f1禁用
      state3: false, //f1禁用
      pattern1: "",
      power1: "",
      standard1: "", //standard1
      frequency1: "",
      dpgrZbpl1: "",
      tpgrZbpl1: "",
      tpgrTzpl1: "",
      tpgrZbpp1: "",
      spgrQspl1: "",
      spgrZzpl1: "",
      spgrSpds1: "",
      spgrPdzlsj1: "",
      bzsgrZxpl1: "",
      bzsgrDk1: "",
      bzsgrLbqxs1: "",
      bzsgrLbqaz1: "",
      txgrZbpl1: "",
      txgrTxxs1: "",
      txgrFhsl1: "",
      txgrPNm1: "",
      txgrLbqxs1: "",
      txgrLbqaz1: "",
      mcgrMckd1: "",
      mcgrZq1: "",
      pattern2: "",
      power2: "",
      standard2: "", //form12
      frequency2: "",
      dpgrZbpl2: "",
      tpgrZbpl2: "",
      tpgrTzpl2: "",
      tpgrZbpp2: "",
      spgrQspl2: "",
      spgrZzpl2: "",
      spgrSpds2: "",
      spgrPdzlsj2: "",
      bzsgrZxpl2: "",
      bzsgrDk2: "",
      bzsgrLbqxs2: "",
      bzsgrLbqaz2: "",
      txgrZbpl2: "",
      txgrTxxs2: "",
      txgrFhsl2: "",
      txgrPNm2: "",
      txgrLbqxs2: "",
      txgrLbqaz2: "",
      mcgrMckd2: "",
      mcgrZq2: "",
      pattern3: "",
      power3: "",
      standard3: "", //form13
      frequency3: "",
      dpgrZbpl3: "",
      tpgrZbpl3: "",
      tpgrTzpl3: "",
      tpgrZbpp3: "",
      spgrQspl3: "",
      spgrZzpl3: "",
      spgrSpds3: "",
      spgrPdzlsj3: "",
      bzsgrZxpl3: "",
      bzsgrDk3: "",
      bzsgrLbqxs3: "",
      bzsgrLbqaz3: "",
      txgrZbpl3: "",
      txgrTxxs3: "",
      txgrFhsl3: "",
      txgrPNm3: "",
      txgrLbqxs3: "",
      txgrLbqaz3: "",
      mcgrMckd3: "",
      mcgrZq3: "",
    },
    form1: {
      f1Bit0: "",
      f1Bit1: "",
      f1Bit2: "",
      f1Bit3: "",
      f2Bit0: "",
      f2Bit1: "",
      f2Bit2: "",
      f2Bit3: "",
      f3Bit0: "",
      f3Bit1: "",
      f3Bit2: "",
      f3Bit3: "",
    },
  },
  {
    name: "从站3",
    id: 3,
    InterfereTime: "", //时间
    grType: "压制干扰", //类型
    grpattern: "", //模式
    homePower: "", //功率
    form: {
      state1: false, //f1禁用
      state2: false, //f1禁用
      state3: false, //f1禁用
      pattern1: "",
      power1: "",
      standard1: "", //standard1
      frequency1: "",
      dpgrZbpl1: "",
      tpgrZbpl1: "",
      tpgrTzpl1: "",
      tpgrZbpp1: "",
      spgrQspl1: "",
      spgrZzpl1: "",
      spgrSpds1: "",
      spgrPdzlsj1: "",
      bzsgrZxpl1: "",
      bzsgrDk1: "",
      bzsgrLbqxs1: "",
      bzsgrLbqaz1: "",
      txgrZbpl1: "",
      txgrTxxs1: "",
      txgrFhsl1: "",
      txgrPNm1: "",
      txgrLbqxs1: "",
      txgrLbqaz1: "",
      mcgrMckd1: "",
      mcgrZq1: "",
      pattern2: "",
      power2: "",
      standard2: "", //form12
      frequency2: "",
      dpgrZbpl2: "",
      tpgrZbpl2: "",
      tpgrTzpl2: "",
      tpgrZbpp2: "",
      spgrQspl2: "",
      spgrZzpl2: "",
      spgrSpds2: "",
      spgrPdzlsj2: "",
      bzsgrZxpl2: "",
      bzsgrDk2: "",
      bzsgrLbqxs2: "",
      bzsgrLbqaz2: "",
      txgrZbpl2: "",
      txgrTxxs2: "",
      txgrFhsl2: "",
      txgrPNm2: "",
      txgrLbqxs2: "",
      txgrLbqaz2: "",
      mcgrMckd2: "",
      mcgrZq2: "",
      pattern3: "",
      power3: "",
      standard3: "", //form13
      frequency3: "",
      dpgrZbpl3: "",
      tpgrZbpl3: "",
      tpgrTzpl3: "",
      tpgrZbpp3: "",
      spgrQspl3: "",
      spgrZzpl3: "",
      spgrSpds3: "",
      spgrPdzlsj3: "",
      bzsgrZxpl3: "",
      bzsgrDk3: "",
      bzsgrLbqxs3: "",
      bzsgrLbqaz3: "",
      txgrZbpl3: "",
      txgrTxxs3: "",
      txgrFhsl3: "",
      txgrPNm3: "",
      txgrLbqxs3: "",
      txgrLbqaz3: "",
      mcgrMckd3: "",
      mcgrZq3: "",
    },
    form1: {
      f1Bit0: "",
      f1Bit1: "",
      f1Bit2: "",
      f1Bit3: "",
      f2Bit0: "",
      f2Bit1: "",
      f2Bit2: "",
      f2Bit3: "",
      f3Bit0: "",
      f3Bit1: "",
      f3Bit2: "",
      f3Bit3: "",
    },
  },
];
