// 站点数据集合
export const tabItemData = [
  {
    name: "主站1",
    id: 0,
    InterfereTime: "", //时间
    grType: "2", //类型
    grPattern: "", //模式
    homePower: "", //功率
    jingdu: 0,
    weidu: 0,
    gaodu: 0,
    form: {
      state1: false, //f1禁用
      state2: false, //f1禁用
      state3: false, //f1禁用
      mode1: "",
      power1: "",
      type1: "",
      frequency1: "",
      dpgrZbpl1: "",
      tpgrZbpl1: "",
      tpgrTzpl1: "",
      tpgrZbpp1: "",
      spgrQspl1: "",
      spgrZzpl1: "",
      spgrSpds1: "",
      spgrPdzlsj1: "",
      bzsgrZxpl1: "",
      bzsgrDk1: "",
      bzsgrLbqxs1: "",
      bzsgrLbqaz1: "",
      txgrZbpl1: "",
      txgrTxxs1: "",
      txgrFhsl1: "",
      txgrPNm1: "",
      txgrLbqxs1: "",
      txgrLbqaz1: "",
      mcgrMckd1: "",
      mcgrZq1: "",
      mode2: "",
      power2: "",
      type2: "", //form12
      frequency2: "",
      dpgrZbpl2: "",
      tpgrZbpl2: "",
      tpgrTzpl2: "",
      tpgrZbpp2: "",
      spgrQspl2: "",
      spgrZzpl2: "",
      spgrSpds2: "",
      spgrPdzlsj2: "",
      bzsgrZxpl2: "",
      bzsgrDk2: "",
      bzsgrLbqxs2: "",
      bzsgrLbqaz2: "",
      txgrZbpl2: "",
      txgrTxxs2: "",
      txgrFhsl2: "",
      txgrPNm2: "",
      txgrLbqxs2: "",
      txgrLbqaz2: "",
      mcgrMckd2: "",
      mcgrZq2: "",
      mode3: "",
      power3: "",
      type3: "", //form13
      frequency3: "",
      dpgrZbpl3: "",
      tpgrZbpl3: "",
      tpgrTzpl3: "",
      tpgrZbpp3: "",
      spgrQspl3: "",
      spgrZzpl3: "",
      spgrSpds3: "",
      spgrPdzlsj3: "",
      bzsgrZxpl3: "",
      bzsgrDk3: "",
      bzsgrLbqxs3: "",
      bzsgrLbqaz3: "",
      txgrZbpl3: "",
      txgrTxxs3: "",
      txgrFhsl3: "",
      txgrPNm3: "",
      txgrLbqxs3: "",
      txgrLbqaz3: "",
      mcgrMckd3: "",
      mcgrZq3: "",
    },
    form1: {
      f1Bit0: "",
      f1Bit1: "",
      f1Bit2: "",
      f1Bit3: "",
      f2Bit0: "",
      f2Bit1: "",
      f2Bit2: "",
      f2Bit3: "",
      f3Bit0: "",
      f3Bit1: "",
      f3Bit2: "",
      f3Bit3: "",
    },
  },
  {
    name: "从站1",
    id: 1,
    InterfereTime: "", //时间
    grType: "2", //类型
    grPattern: "", //模式
    homePower: "", //功率
    jingdu: 0,
    weidu: 0,
    gaodu: 0,
    form: {
      state1: false, //f1禁用
      state2: false, //f1禁用
      state3: false, //f1禁用
      mode1: "",
      power1: "",
      type1: "",
      frequency1: "",
      dpgrZbpl1: "",
      tpgrZbpl1: "",
      tpgrTzpl1: "",
      tpgrZbpp1: "",
      spgrQspl1: "",
      spgrZzpl1: "",
      spgrSpds1: "",
      spgrPdzlsj1: "",
      bzsgrZxpl1: "",
      bzsgrDk1: "",
      bzsgrLbqxs1: "",
      bzsgrLbqaz1: "",
      txgrZbpl1: "",
      txgrTxxs1: "",
      txgrFhsl1: "",
      txgrPNm1: "",
      txgrLbqxs1: "",
      txgrLbqaz1: "",
      mcgrMckd1: "",
      mcgrZq1: "",
      mode2: "",
      power2: "",
      type2: "", //form12
      frequency2: "",
      dpgrZbpl2: "",
      tpgrZbpl2: "",
      tpgrTzpl2: "",
      tpgrZbpp2: "",
      spgrQspl2: "",
      spgrZzpl2: "",
      spgrSpds2: "",
      spgrPdzlsj2: "",
      bzsgrZxpl2: "",
      bzsgrDk2: "",
      bzsgrLbqxs2: "",
      bzsgrLbqaz2: "",
      txgrZbpl2: "",
      txgrTxxs2: "",
      txgrFhsl2: "",
      txgrPNm2: "",
      txgrLbqxs2: "",
      txgrLbqaz2: "",
      mcgrMckd2: "",
      mcgrZq2: "",
      mode3: "",
      power3: "",
      type3: "", //form13
      frequency3: "",
      dpgrZbpl3: "",
      tpgrZbpl3: "",
      tpgrTzpl3: "",
      tpgrZbpp3: "",
      spgrQspl3: "",
      spgrZzpl3: "",
      spgrSpds3: "",
      spgrPdzlsj3: "",
      bzsgrZxpl3: "",
      bzsgrDk3: "",
      bzsgrLbqxs3: "",
      bzsgrLbqaz3: "",
      txgrZbpl3: "",
      txgrTxxs3: "",
      txgrFhsl3: "",
      txgrPNm3: "",
      txgrLbqxs3: "",
      txgrLbqaz3: "",
      mcgrMckd3: "",
      mcgrZq3: "",
    },
    form1: {
      f1Bit0: "",
      f1Bit1: "",
      f1Bit2: "",
      f1Bit3: "",
      f2Bit0: "",
      f2Bit1: "",
      f2Bit2: "",
      f2Bit3: "",
      f3Bit0: "",
      f3Bit1: "",
      f3Bit2: "",
      f3Bit3: "",
    },
  },
  {
    name: "从站2",
    id: 2,
    InterfereTime: "", //时间
    grType: "2", //类型
    grPattern: "", //模式
    homePower: "", //功率
    jingdu: 0,
    weidu: 0,
    gaodu: 0,
    form: {
      state1: false, //f1禁用
      state2: false, //f1禁用
      state3: false, //f1禁用
      mode1: "",
      power1: "",
      type1: "",
      frequency1: "",
      dpgrZbpl1: "",
      tpgrZbpl1: "",
      tpgrTzpl1: "",
      tpgrZbpp1: "",
      spgrQspl1: "",
      spgrZzpl1: "",
      spgrSpds1: "",
      spgrPdzlsj1: "",
      bzsgrZxpl1: "",
      bzsgrDk1: "",
      bzsgrLbqxs1: "",
      bzsgrLbqaz1: "",
      txgrZbpl1: "",
      txgrTxxs1: "",
      txgrFhsl1: "",
      txgrPNm1: "",
      txgrLbqxs1: "",
      txgrLbqaz1: "",
      mcgrMckd1: "",
      mcgrZq1: "",
      mode2: "",
      power2: "",
      type2: "", //form12
      frequency2: "",
      dpgrZbpl2: "",
      tpgrZbpl2: "",
      tpgrTzpl2: "",
      tpgrZbpp2: "",
      spgrQspl2: "",
      spgrZzpl2: "",
      spgrSpds2: "",
      spgrPdzlsj2: "",
      bzsgrZxpl2: "",
      bzsgrDk2: "",
      bzsgrLbqxs2: "",
      bzsgrLbqaz2: "",
      txgrZbpl2: "",
      txgrTxxs2: "",
      txgrFhsl2: "",
      txgrPNm2: "",
      txgrLbqxs2: "",
      txgrLbqaz2: "",
      mcgrMckd2: "",
      mcgrZq2: "",
      mode3: "",
      power3: "",
      type3: "", //form13
      frequency3: "",
      dpgrZbpl3: "",
      tpgrZbpl3: "",
      tpgrTzpl3: "",
      tpgrZbpp3: "",
      spgrQspl3: "",
      spgrZzpl3: "",
      spgrSpds3: "",
      spgrPdzlsj3: "",
      bzsgrZxpl3: "",
      bzsgrDk3: "",
      bzsgrLbqxs3: "",
      bzsgrLbqaz3: "",
      txgrZbpl3: "",
      txgrTxxs3: "",
      txgrFhsl3: "",
      txgrPNm3: "",
      txgrLbqxs3: "",
      txgrLbqaz3: "",
      mcgrMckd3: "",
      mcgrZq3: "",
    },
    form1: {
      f1Bit0: "",
      f1Bit1: "",
      f1Bit2: "",
      f1Bit3: "",
      f2Bit0: "",
      f2Bit1: "",
      f2Bit2: "",
      f2Bit3: "",
      f3Bit0: "",
      f3Bit1: "",
      f3Bit2: "",
      f3Bit3: "",
    },
  },
  {
    name: "从站3",
    id: 3,
    InterfereTime: "", //时间
    grType: "2", //类型
    grPattern: "", //模式
    homePower: "", //功率
    form: {
      state1: false, //f1禁用
      state2: false, //f1禁用
      state3: false, //f1禁用
      mode1: "",
      power1: "",
      type1: "",
      frequency1: "",
      dpgrZbpl1: "",
      tpgrZbpl1: "",
      tpgrTzpl1: "",
      tpgrZbpp1: "",
      spgrQspl1: "",
      spgrZzpl1: "",
      spgrSpds1: "",
      spgrPdzlsj1: "",
      bzsgrZxpl1: "",
      bzsgrDk1: "",
      bzsgrLbqxs1: "",
      bzsgrLbqaz1: "",
      txgrZbpl1: "",
      txgrTxxs1: "",
      txgrFhsl1: "",
      txgrPNm1: "",
      txgrLbqxs1: "",
      txgrLbqaz1: "",
      mcgrMckd1: "",
      mcgrZq1: "",
      mode2: "",
      power2: "",
      type2: "", //form12
      frequency2: "",
      dpgrZbpl2: "",
      tpgrZbpl2: "",
      tpgrTzpl2: "",
      tpgrZbpp2: "",
      spgrQspl2: "",
      spgrZzpl2: "",
      spgrSpds2: "",
      spgrPdzlsj2: "",
      bzsgrZxpl2: "",
      bzsgrDk2: "",
      bzsgrLbqxs2: "",
      bzsgrLbqaz2: "",
      txgrZbpl2: "",
      txgrTxxs2: "",
      txgrFhsl2: "",
      txgrPNm2: "",
      txgrLbqxs2: "",
      txgrLbqaz2: "",
      mcgrMckd2: "",
      mcgrZq2: "",
      mode3: "",
      power3: "",
      type3: "", //form13
      frequency3: "",
      dpgrZbpl3: "",
      tpgrZbpl3: "",
      tpgrTzpl3: "",
      tpgrZbpp3: "",
      spgrQspl3: "",
      spgrZzpl3: "",
      spgrSpds3: "",
      spgrPdzlsj3: "",
      bzsgrZxpl3: "",
      bzsgrDk3: "",
      bzsgrLbqxs3: "",
      bzsgrLbqaz3: "",
      txgrZbpl3: "",
      txgrTxxs3: "",
      txgrFhsl3: "",
      txgrPNm3: "",
      txgrLbqxs3: "",
      txgrLbqaz3: "",
      mcgrMckd3: "",
      mcgrZq3: "",
    },
    form1: {
      f1Bit0: "",
      f1Bit1: "",
      f1Bit2: "",
      f1Bit3: "",
      f2Bit0: "",
      f2Bit1: "",
      f2Bit2: "",
      f2Bit3: "",
      f3Bit0: "",
      f3Bit1: "",
      f3Bit2: "",
      f3Bit3: "",
    },
  },
];
// 公共干扰频数据
export const commonFrequency = [
  { value: "1", label: "GPS-L1" },
  { value: "2", label: "GPS-L2" },
  { value: "3", label: "GLONASS-G1" },
  { value: "4", label: "BD/BD3-B1I" },
  { value: "5", label: "BD/BD3-B2I" },
  { value: "6", label: "BD/BD3-B3I" },
  { value: "7", label: "BD/BD3-B1C" },
  { value: "8", label: "BD/BD3-B2a" },
  { value: "9", label: "BD/BD3-B2b" },
];
// 干扰模式数据
export const pattern = [
  {
    value: "0",
    label: "固定源端功1",
  },
  {
    value: "1",
    label: "固定目标处功1",
  },
  {
    value: "2",
    label: "固定指向和源端功1",
  },
];
// 调相干扰下拉数据
export const txgrPNm = [
  { value: "1", label: "0:PN9" },
  { value: "2", label: "1:PN11" },
  { value: "3", label: "2:PN15" },
  { value: "4", label: "3:PN20" },
  { value: "5", label: "4:PN23" },
];
// 干扰制式
export const standard = [
  { value: "0", label: "点频干扰" },
  { value: "1", label: "调频干扰" },
  { value: "2", label: "扫频干扰" },
  { value: "3", label: "白噪声干扰" },
  { value: "4", label: "调相干扰" },
  { value: "9", label: "脉冲干扰" },
  { value: "255", label: "无效干扰" },
];
